### ISSUE TITLE
Expected_release_date is nil for all games

### ISSUE THREAD

**Issue by joekw** [davefoxy/SwiftBomb#1]
Returning expected_release_date while searching for games is meant to return the expected month and year of the games release date. This is blank for all games i've searched.
Using the extendedinfo version is also blank for all games.

**Comment by davefoxy** [comment]
Sorry for the late reply @joekw 
This seems to work for me...

```
SwiftBomb.fetchGames("no man's sky") { (results, error) in

       if let firstGame = results?.resources.first {
           print("\(firstGame.name) - \(firstGame.expected_release_date)")
       }
   }
```

It correctly returns "No Man's Sky - 2016-07-31 23:00:00 +0000" which is what the API returns. Can you give me an example of a call that's not working please? I'm guessing maybe the particular game you searched for might not have it's expected date in the wiki. Does the actual request the library is making, when pasted into a browser, show the date coming back in the JSON?

Note: The above example will stop returning the expected release date when the game comes out on the 31st ;)

**Comment by joekw** [comment]
Welp, that's embarrassing. I had "expected_release_date" in the fields list which obviously won't return anything from the API.

All fine now, thanks!

(Thanks so much for this framework btw, i would never have got my app working without it!

**Comment by davefoxy** [comment]
@joekw Great! I'll close this issue now. Do share your app once you're finished. I'd love to see what people come up with using it. Also, feel free to drop any feature requests my way.
